export const RARITY_META = Object.freeze({
  common: Object.freeze({ rank: 1, label: 'COMMON', color: '#b8c0cc' }),
  rare: Object.freeze({ rank: 2, label: 'RARE', color: '#5aa9ff' }),
  epic: Object.freeze({ rank: 3, label: 'EPIC', color: '#c07bff' }),
  legendary: Object.freeze({ rank: 4, label: 'LEGENDARY', color: '#ffb43a' }),
  mythic: Object.freeze({ rank: 5, label: 'MYTHIC', color: '#d9a7ff' }),
});

const records = [
  { id: 'poring', itemName: 'Poring Card', displayName: 'Poring', collectionNo: 'C-01', rarity: 'common', slot: 'armor', art: '/assets/cards/poring.webp', abilityName: 'Gelatin Guard', stats: { hpBonus: 80 }, effect: null, source: { kind: 'monster', id: 'poring', label: 'Poring · Prontera Field', chance: 0.02, pity: 100 }, lore: 'A soft heart that hardens when its owner is threatened.', legacyAliases: ['Poring Card'] },
  { id: 'willow', itemName: 'Willow Card', displayName: 'Willow', collectionNo: 'C-02', rarity: 'common', slot: 'weapon', art: '/assets/cards/willow.webp', abilityName: 'Rooted Strike', stats: { atkBonus: 8 }, effect: null, source: { kind: 'monster', id: 'willow', label: 'Willow · Prontera Field', chance: 0.02, pity: 100 }, lore: 'Ancient roots lend every swing a patient, unyielding force.', legacyAliases: ['Willow Card', 'Andre Card'] },
  { id: 'lunatic', itemName: 'Lunatic Card', displayName: 'Lunatic', collectionNo: 'C-03', rarity: 'common', slot: 'accessory', art: '/assets/cards/lunatic.webp', abilityName: 'Moon Instinct', stats: {}, effect: { type: 'critBonus', value: 0.03 }, source: { kind: 'monster', id: 'lunatic', label: 'Lunatic · Prontera Field', chance: 0.02, pity: 100 }, lore: 'Moonlit ears twitch just before fortune finds its mark.', legacyAliases: ['Lunatic Card'] },
  { id: 'fabre', itemName: 'Fabre Card', displayName: 'Fabre', collectionNo: 'C-04', rarity: 'common', slot: 'armor', art: '/assets/cards/fabre.webp', abilityName: 'Soft Carapace', stats: { hpBonus: 70, defBonus: 2 }, effect: null, source: { kind: 'monster', id: 'fabre', label: 'Fabre · Prontera Field', chance: 0.02, pity: 100 }, lore: 'Its small shell bends before it ever breaks.', legacyAliases: ['Fabre Card'] },
  { id: 'rocker', itemName: 'Rocker Card', displayName: 'Rocker', collectionNo: 'C-05', rarity: 'common', slot: 'accessory', art: '/assets/cards/rocker.webp', abilityName: 'Battle Rhythm', stats: { atkBonus: 6 }, effect: null, source: { kind: 'monster', id: 'rocker', label: 'Rocker · Prontera Field', chance: 0.02, pity: 100 }, lore: 'A restless tune keeps a fighter moving through the fray.', legacyAliases: ['Rocker Card'] },
  { id: 'horn', itemName: 'Horn Card', displayName: 'Horn', collectionNo: 'C-06', rarity: 'common', slot: 'shield', art: '/assets/cards/horn.webp', abilityName: 'Shell Guard', stats: { defBonus: 7 }, effect: null, source: { kind: 'monster', id: 'horn', label: 'Horn · Payon Forest', chance: 0.02, pity: 100 }, lore: 'A polished horn remembers every blow it has endured.', legacyAliases: [] },
  { id: 'spore', itemName: 'Spore Card', displayName: 'Spore', collectionNo: 'C-07', rarity: 'common', slot: 'armor', art: '/assets/cards/spore.webp', abilityName: 'Spore Vitality', stats: { hpBonus: 90 }, effect: null, source: { kind: 'monster', id: 'spore', label: 'Spore · Payon Forest', chance: 0.02, pity: 100 }, lore: 'A cloud of quiet life clings close to its bearer.', legacyAliases: [] },
  { id: 'shrimp', itemName: 'Shrimp Card', displayName: 'Shrimp', collectionNo: 'C-08', rarity: 'common', slot: 'accessory', art: '/assets/cards/shrimp.webp', abilityName: 'River Energy', stats: { spBonus: 18 }, effect: null, source: { kind: 'monster', id: 'shrimp', label: 'Shrimp · Waterway', chance: 0.02, pity: 100 }, lore: 'Swift river currents carry a spark of clear focus.', legacyAliases: [] },
  { id: 'clam', itemName: 'Clam Card', displayName: 'Clam', collectionNo: 'C-09', rarity: 'common', slot: 'shield', art: '/assets/cards/clam.webp', abilityName: 'Pearl Shell', stats: { defBonus: 6, hpBonus: 30 }, effect: null, source: { kind: 'monster', id: 'clam', label: 'Clam · Waterway', chance: 0.02, pity: 100 }, lore: 'A pearl-bright shell closes around a resilient spirit.', legacyAliases: [] },
  { id: 'fish', itemName: 'Fish Card', displayName: 'Fish', collectionNo: 'C-10', rarity: 'common', slot: 'accessory', art: '/assets/cards/fish.webp', abilityName: 'Fresh Catch', stats: { spBonus: 12, hpBonus: 35 }, effect: null, source: { kind: 'monster', id: 'fish', label: 'Fish · Waterway', chance: 0.02, pity: 100 }, lore: 'A clean current restores what a long hunt has spent.', legacyAliases: [] },
  { id: 'crab', itemName: 'Crab Card', displayName: 'Crab', collectionNo: 'C-11', rarity: 'common', slot: 'shield', art: '/assets/cards/crab.webp', abilityName: 'Sideguard', stats: { defBonus: 8 }, effect: null, source: { kind: 'monster', id: 'crab', label: 'Crab · Waterway', chance: 0.02, pity: 100 }, lore: 'Its sideways stance leaves no opening unguarded.', legacyAliases: ['Vadon Card'] },
  { id: 'dragon_egg', itemName: 'Dragon Egg Card', displayName: 'Dragon Egg', collectionNo: 'C-12', rarity: 'common', slot: 'armor', art: '/assets/cards/dragon_egg.webp', abilityName: 'Dormant Scale', stats: { hpBonus: 110 }, effect: null, source: { kind: 'monster', id: 'dragon_egg', label: 'Dragon Egg · Waterway', chance: 0.02, pity: 100 }, lore: 'Beneath the shell, a future dragon gathers its strength.', legacyAliases: ['Pupa Card'] },

  { id: 'poporing', itemName: 'Poporing Card', displayName: 'Poporing', collectionNo: 'R-01', rarity: 'rare', slot: 'weapon', art: '/assets/cards/poporing.webp', abilityName: 'Acid Body', stats: { atkBonus: 14 }, effect: { type: 'damageToFamily', family: 'slime', value: 0.05 }, source: { kind: 'monster', id: 'poporing', label: 'Poporing · Prontera Field', chance: 0.0075, pity: 250 }, lore: 'A caustic core turns every strike against slime into a lesson.', legacyAliases: [] },
  { id: 'drops', itemName: 'Drops Card', displayName: 'Drops', collectionNo: 'R-02', rarity: 'rare', slot: 'accessory', art: '/assets/cards/drops.webp', abilityName: 'Lucky Drop', stats: {}, effect: { type: 'dropRatePct', value: 0.03 }, source: { kind: 'monster', id: 'drops', label: 'Drops · Prontera Field', chance: 0.0075, pity: 250 }, lore: 'A bright little charm that makes the next find feel closer.', legacyAliases: [] },
  { id: 'savage', itemName: 'Savage Card', displayName: 'Savage', collectionNo: 'R-03', rarity: 'rare', slot: 'armor', art: '/assets/cards/savage.webp', abilityName: 'Wild Hide', stats: { hpBonus: 160, defBonus: 4 }, effect: null, source: { kind: 'monster', id: 'savage', label: 'Savage · Payon Forest', chance: 0.0075, pity: 250 }, lore: 'A rough hide carries the stubbornness of the wild.', legacyAliases: [] },
  { id: 'boa', itemName: 'Boa Card', displayName: 'Boa', collectionNo: 'R-04', rarity: 'rare', slot: 'weapon', art: '/assets/cards/boa.webp', abilityName: 'Venom Fang', stats: { atkBonus: 18 }, effect: null, source: { kind: 'monster', id: 'boa', label: 'Boa · Payon Forest', chance: 0.0075, pity: 250 }, lore: 'Its patient coil lends a venomous precision to each attack.', legacyAliases: [] },
  { id: 'bigfoot', itemName: 'Bigfoot Card', displayName: 'Bigfoot', collectionNo: 'R-05', rarity: 'rare', slot: 'armor', art: '/assets/cards/bigfoot.webp', abilityName: 'Forest Bulk', stats: { hpBonus: 190 }, effect: null, source: { kind: 'monster', id: 'bigfoot', label: 'Bigfoot · Payon Forest', chance: 0.0075, pity: 250 }, lore: 'Deep forest strength stands broad and immovable.', legacyAliases: [] },
  { id: 'nine_tail', itemName: 'Nine Tail Card', displayName: 'Nine Tail', collectionNo: 'R-06', rarity: 'rare', slot: 'accessory', art: '/assets/cards/nine_tail.webp', abilityName: 'Foxfire Focus', stats: {}, effect: { type: 'critBonus', value: 0.05 }, source: { kind: 'monster', id: 'nine_tail', label: 'Nine Tail · Payon Forest', chance: 0.0075, pity: 250 }, lore: 'Nine flickering tails point toward a single perfect opening.', legacyAliases: [] },
  { id: 'skeleton', itemName: 'Skeleton Card', displayName: 'Skeleton', collectionNo: 'R-07', rarity: 'rare', slot: 'weapon', art: '/assets/cards/skeleton.webp', abilityName: 'Bone Edge', stats: { atkBonus: 22 }, effect: null, source: { kind: 'monster', id: 'skeleton', label: 'Skeleton · Glast Heim', chance: 0.0075, pity: 250 }, lore: 'A splinter of old resolve sharpens an ordinary blade.', legacyAliases: ['Skeleton Card'] },
  { id: 'zombie', itemName: 'Zombie Card', displayName: 'Zombie', collectionNo: 'R-08', rarity: 'rare', slot: 'armor', art: '/assets/cards/zombie.webp', abilityName: 'Undying Flesh', stats: { hpBonus: 180 }, effect: { type: 'onKillRestore', hp: 6 }, source: { kind: 'monster', id: 'zombie', label: 'Zombie · Glast Heim', chance: 0.0075, pity: 250 }, lore: 'Even after the last blow, its will insists on rising again.', legacyAliases: [] },
  { id: 'hunter_fly', itemName: 'Hunter Fly Card', displayName: 'Hunter Fly', collectionNo: 'R-09', rarity: 'rare', slot: 'accessory', art: '/assets/cards/hunter_fly.webp', abilityName: 'Blood Wing', stats: {}, effect: { type: 'lifestealPct', value: 0.02 }, source: { kind: 'monster', id: 'hunter_fly', label: 'Hunter Fly · Glast Heim', chance: 0.0075, pity: 250 }, lore: 'A hungry flutter returns a measure of life to the hunter.', legacyAliases: [] },
  { id: 'golem', itemName: 'Golem Card', displayName: 'Golem', collectionNo: 'R-10', rarity: 'rare', slot: 'shield', art: '/assets/cards/golem.webp', abilityName: 'Stone Body', stats: { defBonus: 15 }, effect: null, source: { kind: 'monster', id: 'golem', label: 'Golem · Mjolnir', chance: 0.0075, pity: 250 }, lore: 'A quiet stone heart gives shape to stubborn defense.', legacyAliases: ['Sohee Card'] },
  { id: 'marina', itemName: 'Marina Card', displayName: 'Marina', collectionNo: 'R-11', rarity: 'rare', slot: 'armor', art: '/assets/cards/marina.webp', abilityName: 'Tidal Heart', stats: { hpBonus: 150, spBonus: 28 }, effect: null, source: { kind: 'monster', id: 'marina', label: 'Marina · Waterway', chance: 0.0075, pity: 250 }, lore: 'The tide leaves strength behind with every measured breath.', legacyAliases: ['Marina Card'] },
  { id: 'sea_dragon', itemName: 'Sea Dragon Card', displayName: 'Sea Dragon', collectionNo: 'R-12', rarity: 'rare', slot: 'weapon', art: '/assets/cards/sea_dragon.webp', abilityName: 'Riptide Claw', stats: { atkBonus: 20 }, effect: { type: 'bossDamagePct', value: 0.02 }, source: { kind: 'monster', id: 'sea_dragon', label: 'Sea Dragon · Waterway', chance: 0.0075, pity: 250 }, lore: 'A riptide-born claw finds purchase even on colossal prey.', legacyAliases: [] },

  { id: 'deviruchi', itemName: 'Deviruchi Card', displayName: 'Deviruchi', collectionNo: 'E-01', rarity: 'epic', slot: 'weapon', art: '/assets/cards/deviruchi.webp', abilityName: 'Devil’s Bargain', stats: { atkBonus: 30 }, effect: { type: 'damagePct', value: 0.04 }, source: { kind: 'monster', id: 'deviruchi', label: 'Deviruchi · Prontera Cave', chance: 0.002, pity: 500 }, lore: 'A small devil always collects on the power it promises.', legacyAliases: ['Goblin Card'] },
  { id: 'ghostring', itemName: 'Ghostring Card', displayName: 'Ghostring', collectionNo: 'E-02', rarity: 'epic', slot: 'accessory', art: '/assets/cards/ghostring.webp', abilityName: 'Phase Drain', stats: { spBonus: 25 }, effect: { type: 'lifestealPct', value: 0.04 }, source: { kind: 'monster', id: 'ghostring', label: 'Ghostring · Prontera Cave', chance: 0.002, pity: 500 }, lore: 'A spectral hunger slips through armor and returns as strength.', legacyAliases: ['Ghostring Card'] },
  { id: 'archer_skeleton', itemName: 'Archer Skeleton Card', displayName: 'Archer Skeleton', collectionNo: 'E-03', rarity: 'epic', slot: 'weapon', art: '/assets/cards/archer_skeleton.webp', abilityName: 'Deadeye', stats: { atkBonus: 24 }, effect: { type: 'critBonus', value: 0.06 }, source: { kind: 'monster', id: 'archer_skeleton', label: 'Archer Skeleton · Glast Heim', chance: 0.002, pity: 500 }, lore: 'The arrow has already found its mark before the bowstring sings.', legacyAliases: [] },
  { id: 'raydric', itemName: 'Raydric Card', displayName: 'Raydric', collectionNo: 'E-04', rarity: 'epic', slot: 'armor', art: '/assets/cards/raydric.webp', abilityName: 'Royal Guard', stats: { defBonus: 18 }, effect: { type: 'damageReduction', value: 0.03 }, source: { kind: 'monster', id: 'raydric', label: 'Raydric · Glast Heim', chance: 0.002, pity: 500 }, lore: 'A knight’s oath turns an incoming blow aside at the last instant.', legacyAliases: [] },
  { id: 'harpy', itemName: 'Harpy Card', displayName: 'Harpy', collectionNo: 'E-05', rarity: 'epic', slot: 'accessory', art: '/assets/cards/harpy.webp', abilityName: 'Gale Reflex', stats: { spBonus: 35 }, effect: { type: 'critBonus', value: 0.07 }, source: { kind: 'monster', id: 'harpy', label: 'Harpy · Mjolnir', chance: 0.002, pity: 500 }, lore: 'A gale’s warning lets a hunter strike in the space between breaths.', legacyAliases: ['Mantis Card'] },
  { id: 'gargoyle', itemName: 'Gargoyle Card', displayName: 'Gargoyle', collectionNo: 'E-06', rarity: 'epic', slot: 'shield', art: '/assets/cards/gargoyle.webp', abilityName: 'Granite Wings', stats: { defBonus: 22, hpBonus: 150 }, effect: null, source: { kind: 'monster', id: 'gargoyle', label: 'Gargoyle · Glast Heim', chance: 0.002, pity: 500 }, lore: 'Stone wings fold around their bearer when danger draws near.', legacyAliases: [] },
  { id: 'stone_golem', itemName: 'Stone Golem Card', displayName: 'Stone Golem', collectionNo: 'E-07', rarity: 'epic', slot: 'armor', art: '/assets/cards/stone_golem.webp', abilityName: 'Mountain Core', stats: { hpBonus: 300, defBonus: 12 }, effect: null, source: { kind: 'monster', id: 'stone_golem', label: 'Stone Golem · Mjolnir', chance: 0.002, pity: 500 }, lore: 'A mountain’s core beats slowly beneath a mantle of stone.', legacyAliases: [] },
  { id: 'iron_golem', itemName: 'Iron Golem Card', displayName: 'Iron Golem', collectionNo: 'E-08', rarity: 'epic', slot: 'shield', art: '/assets/cards/iron_golem.webp', abilityName: 'Iron Bastion', stats: { defBonus: 28 }, effect: null, source: { kind: 'monster', id: 'iron_golem', label: 'Iron Golem · Mjolnir', chance: 0.002, pity: 500 }, lore: 'Forged plates lock together into a wall that will not yield.', legacyAliases: [] },
  { id: 'leib_olmai', itemName: 'Leib Olmai Card', displayName: 'Leib Olmai', collectionNo: 'E-09', rarity: 'epic', slot: 'weapon', art: '/assets/cards/leib_olmai.webp', abilityName: 'Flame Rend', stats: { atkBonus: 34 }, effect: { type: 'damageToFamily', family: 'beast', value: 0.08 }, source: { kind: 'monster', id: 'leib_olmai', label: 'Leib Olmai · Mjolnir', chance: 0.002, pity: 500 }, lore: 'A burning claw teaches wild beasts to fear the flame.', legacyAliases: [] },
  { id: 'dark_illusion', itemName: 'Dark Illusion Card', displayName: 'Dark Illusion', collectionNo: 'E-10', rarity: 'epic', slot: 'accessory', art: '/assets/cards/dark_illusion.webp', abilityName: 'Shadow Hunger', stats: { lifestealPct: 0.02 }, effect: { type: 'damagePct', value: 0.05 }, source: { kind: 'monster', id: 'dark_illusion', label: 'Dark Illusion · Glast Heim', chance: 0.002, pity: 500 }, lore: 'A shadow feeds on the brief confusion before an enemy falls.', legacyAliases: [] },
  { id: 'abyss_knight', itemName: 'Abyss Knight Card', displayName: 'Abyss Knight', collectionNo: 'E-11', rarity: 'epic', slot: 'weapon', art: '/assets/cards/abyss_knight.webp', abilityName: 'Abyssal Edge', stats: { atkBonus: 38 }, effect: { type: 'bossDamagePct', value: 0.05 }, source: { kind: 'monster', id: 'abyss_knight', label: 'Abyss Knight · Abyss', chance: 0.002, pity: 500 }, lore: 'An edge honed in the abyss seeks the heart of mighty foes.', legacyAliases: [] },
  { id: 'storm_dragon', itemName: 'Storm Dragon Card', displayName: 'Storm Dragon', collectionNo: 'E-12', rarity: 'epic', slot: 'armor', art: '/assets/cards/storm_dragon.webp', abilityName: 'Storm Scale', stats: { hpBonus: 320 }, effect: { type: 'damageReduction', value: 0.04 }, source: { kind: 'monster', id: 'storm_dragon', label: 'Storm Dragon · Abyss', chance: 0.002, pity: 500 }, lore: 'Each charged scale disperses a little of the storm’s fury.', legacyAliases: [] },

  { id: 'dullahan', itemName: 'Dullahan Card', displayName: 'Dullahan', collectionNo: 'L-01', rarity: 'legendary', slot: 'weapon', art: '/assets/cards/dullahan.webp', abilityName: 'Headless Pursuit', stats: { atkBonus: 45 }, effect: { type: 'executePct', value: 0.05 }, source: { kind: 'mapBoss', id: 'dullahan', label: 'Dullahan · Glast Heim map-boss clear', chance: 0.015, pity: 50 }, lore: 'A relentless pursuit ends only when the last sliver of hope is gone.', legacyAliases: [] },
  { id: 'ghostring_prime', itemName: 'Ghostring Prime Card', displayName: 'Ghostring Prime', collectionNo: 'L-02', rarity: 'legendary', slot: 'accessory', art: '/assets/cards/ghostring_prime.webp', abilityName: 'Ethereal Feast', stats: { critBonus: 0.04 }, effect: { type: 'lifestealPct', value: 0.06 }, source: { kind: 'event', id: 'ghostring_elite', label: 'Ghostring elite event', chance: 0.015, pity: 50 }, lore: 'A perfected phantom feasts on both fear and falling starlight.', legacyAliases: [] },
  { id: 'angeling', itemName: 'Angeling Card', displayName: 'Angeling', collectionNo: 'L-03', rarity: 'legendary', slot: 'armor', art: '/assets/cards/angeling.webp', abilityName: 'Holy Sanctuary', stats: { hpBonus: 480, defBonus: 14 }, effect: null, source: { kind: 'event', id: 'prontera_holy', label: 'Prontera holy event', chance: 0.015, pity: 50 }, lore: 'A fragment of sanctuary remains wherever this blessing is carried.', legacyAliases: ['Angeling Card'] },
  { id: 'golden_thief_bug', itemName: 'Golden Thief Bug Card', displayName: 'Golden Thief Bug', collectionNo: 'L-04', rarity: 'legendary', slot: 'shield', art: '/assets/cards/golden_thief_bug.webp', abilityName: 'Golden Carapace', stats: { defBonus: 30 }, effect: { type: 'damageReduction', value: 0.05 }, source: { kind: 'event', id: 'mjolnir_elite', label: 'Mjolnir elite event', chance: 0.015, pity: 50 }, lore: 'A stolen sheen turns hard shell into an impossible defense.', legacyAliases: ['Golden Thief Bug Card'] },
  { id: 'doppelganger', itemName: 'Doppelganger Card', displayName: 'Doppelganger', collectionNo: 'L-05', rarity: 'legendary', slot: 'weapon', art: '/assets/cards/doppelganger.webp', abilityName: 'Mirror Assault', stats: { atkBonus: 44, critBonus: 0.04 }, effect: { type: 'damagePct', value: 0.08 }, source: { kind: 'event', id: 'glast_heim_elite', label: 'Glast Heim elite event', chance: 0.015, pity: 50 }, lore: 'Every attack seems to arrive twice, once from each reflection.', legacyAliases: ['Doppelganger Card'] },
  { id: 'maya', itemName: 'Maya Card', displayName: 'Maya', collectionNo: 'L-06', rarity: 'legendary', slot: 'accessory', art: '/assets/cards/maya.webp', abilityName: 'Queen’s Command', stats: { atkBonus: 18 }, effect: { type: 'critBonus', value: 0.08 }, source: { kind: 'event', id: 'payon_colony', label: 'Payon colony event', chance: 0.015, pity: 50 }, lore: 'The queen’s command makes every worker’s strike count.', legacyAliases: [] },
  { id: 'baphomet', itemName: 'Baphomet Card', displayName: 'Baphomet', collectionNo: 'L-07', rarity: 'legendary', slot: 'weapon', art: '/assets/cards/baphomet.webp', abilityName: 'Crescent Ruin', stats: { atkBonus: 50 }, effect: { type: 'bossDamagePct', value: 0.07 }, source: { kind: 'event', id: 'glast_heim_raid', label: 'Glast Heim raid', chance: 0.015, pity: 50 }, lore: 'A ruined crescent cuts deepest into rulers of the battlefield.', legacyAliases: [] },
  { id: 'drake', itemName: 'Drake Card', displayName: 'Drake', collectionNo: 'L-08', rarity: 'legendary', slot: 'accessory', art: '/assets/cards/drake.webp', abilityName: 'Drowned Fortune', stats: { lifestealPct: 0.05 }, effect: { type: 'dropRatePct', value: 0.05 }, source: { kind: 'event', id: 'water_festival_raid', label: 'Water festival raid', chance: 0.015, pity: 50 }, lore: 'Sunken treasure keeps finding its way back to a lucky hand.', legacyAliases: [] },
  { id: 'moonlight_flower', itemName: 'Moonlight Flower Card', displayName: 'Moonlight Flower', collectionNo: 'L-09', rarity: 'legendary', slot: 'accessory', art: '/assets/cards/moonlight_flower.webp', abilityName: 'Lunar Grace', stats: { spBonus: 65 }, effect: { type: 'critBonus', value: 0.09 }, source: { kind: 'event', id: 'payon_moon', label: 'Payon moon event', chance: 0.015, pity: 50 }, lore: 'Moon petals settle softly over the path to a flawless strike.', legacyAliases: [] },
  { id: 'turtle_general', itemName: 'Turtle General Card', displayName: 'Turtle General', collectionNo: 'L-10', rarity: 'legendary', slot: 'shield', art: '/assets/cards/turtle_general.webp', abilityName: 'General’s Bulwark', stats: { defBonus: 34, hpBonus: 260 }, effect: null, source: { kind: 'event', id: 'water_fortress', label: 'Water fortress event', chance: 0.015, pity: 50 }, lore: 'A seasoned commander turns a shield into a fortified line.', legacyAliases: [] },
  { id: 'samurai_specter', itemName: 'Samurai Specter Card', displayName: 'Samurai Specter', collectionNo: 'L-11', rarity: 'legendary', slot: 'armor', art: '/assets/cards/samurai_specter.webp', abilityName: 'Last Stand', stats: { hpBonus: 360 }, effect: { type: 'lowHpPower', threshold: 0.3, value: 0.1 }, source: { kind: 'event', id: 'glast_heim_specter', label: 'Glast Heim specter event', chance: 0.015, pity: 50 }, lore: 'At the edge of defeat, an old warrior’s spirit becomes fearless.', legacyAliases: [] },
  { id: 'valkyrie', itemName: 'Valkyrie Card', displayName: 'Valkyrie', collectionNo: 'L-12', rarity: 'legendary', slot: 'armor', art: '/assets/cards/valkyrie.webp', abilityName: 'Chosen Guard', stats: { hpBonus: 520 }, effect: { type: 'damageReduction', value: 0.04 }, source: { kind: 'event', id: 'celestial_trial', label: 'Celestial trial', chance: 0.015, pity: 50 }, lore: 'A chosen guardian’s blessing refuses to let the worthy fall.', legacyAliases: [] },

  { id: 'valdris', itemName: 'Valdris Card', displayName: 'Valdris', collectionNo: 'M-01', rarity: 'mythic', slot: 'weapon', art: '/assets/cards/valdris.webp', abilityName: 'Infernal Sovereign', stats: { atkBonus: 65 }, effect: { type: 'damagePct', value: 0.12 }, source: { kind: 'world_boss', id: 'valdris', label: 'Valdris world boss', chance: 0.0035, pity: 150 }, lore: 'An infernal crown lends its bearer a sovereign’s devastating force.', legacyAliases: [] },
  { id: 'ignarok', itemName: 'Ignarok Card', displayName: 'Ignarok', collectionNo: 'M-02', rarity: 'mythic', slot: 'armor', art: '/assets/cards/ignarok.webp', abilityName: 'Dragon King', stats: { hpBonus: 700 }, effect: { type: 'bossDamagePct', value: 0.1 }, source: { kind: 'world_boss', id: 'ignarok', label: 'Ignarok world boss', chance: 0.0035, pity: 150 }, lore: 'The Dragon King’s heart pounds louder in the presence of great foes.', legacyAliases: [] },
  { id: 'abyss_golem', itemName: 'Abyss Golem Card', displayName: 'Abyss Golem', collectionNo: 'M-03', rarity: 'mythic', slot: 'shield', art: '/assets/cards/abyss_golem.webp', abilityName: 'Unbroken World', stats: { defBonus: 48 }, effect: { type: 'damageReduction', value: 0.08 }, source: { kind: 'world_boss', id: 'abyss_golem', label: 'Golem of the Deep world boss', chance: 0.0035, pity: 150 }, lore: 'A piece of the unbroken world refuses every attempt to shatter it.', legacyAliases: [] },
  { id: 'morgath', itemName: 'Morgath Card', displayName: 'Morgath', collectionNo: 'M-04', rarity: 'mythic', slot: 'accessory', art: '/assets/cards/morgath.webp', abilityName: 'Soul Devourer', stats: { lifestealPct: 0.09 }, effect: { type: 'onKillRestore', sp: 20 }, source: { kind: 'world_boss', id: 'morgath', label: 'Morgath world boss', chance: 0.0035, pity: 150 }, lore: 'A devoured soul leaves behind a bright, stolen spark of power.', legacyAliases: [] },
  { id: 'kaltharu', itemName: 'Kaltharu Card', displayName: 'Kaltharu', collectionNo: 'M-05', rarity: 'mythic', slot: 'armor', art: '/assets/cards/kaltharu.webp', abilityName: 'Absolute Zero', stats: { hpBonus: 620, defBonus: 32 }, effect: null, source: { kind: 'world_boss', id: 'kaltharu', label: 'Kaltharu world boss', chance: 0.0035, pity: 150 }, lore: 'Perfect cold stills panic and armors the soul in ice.', legacyAliases: [] },
  { id: 'zulgaroth', itemName: 'Zul’garoth Card', displayName: 'Zul’garoth', collectionNo: 'M-06', rarity: 'mythic', slot: 'weapon', art: '/assets/cards/zulgaroth.webp', abilityName: 'Godslayer', stats: { atkBonus: 70 }, effect: { type: 'bossDamagePct', value: 0.14 }, source: { kind: 'world_boss', id: 'zulgaroth', label: 'Zul’garoth world boss', chance: 0.0035, pity: 150 }, lore: 'A godslayer’s mark burns hottest against the strongest enemies.', legacyAliases: [] },
  { id: 'nidhogg', itemName: 'Nidhogg Card', displayName: 'Nidhogg', collectionNo: 'M-07', rarity: 'mythic', slot: 'armor', art: '/assets/cards/nidhogg.webp', abilityName: 'World Eater', stats: { hpBonus: 800 }, effect: { type: 'damagePct', value: 0.08 }, source: { kind: 'event', id: 'abyss_season_finale', label: 'Abyss season finale', chance: 0.0035, pity: 150 }, lore: 'The World Eater leaves nothing untouched by its ravenous shadow.', legacyAliases: [] },
  { id: 'fenrir', itemName: 'Fenrir Card', displayName: 'Fenrir', collectionNo: 'M-08', rarity: 'mythic', slot: 'accessory', art: '/assets/cards/fenrir.webp', abilityName: 'Ragnarok Chase', stats: { critBonus: 0.12 }, effect: { type: 'lowHpPower', threshold: 0.3, value: 0.14 }, source: { kind: 'event', id: 'mjolnir_season_finale', label: 'Mjolnir season finale', chance: 0.0035, pity: 150 }, lore: 'The chase becomes fiercer when the hunter’s own blood runs low.', legacyAliases: [] },
  { id: 'jormungandr', itemName: 'Jormungandr Card', displayName: 'Jormungandr', collectionNo: 'M-09', rarity: 'mythic', slot: 'shield', art: '/assets/cards/jormungandr.webp', abilityName: 'Endless Coil', stats: { defBonus: 44, hpBonus: 500 }, effect: null, source: { kind: 'event', id: 'water_season_finale', label: 'Water season finale', chance: 0.0035, pity: 150 }, lore: 'An endless coil turns back upon itself, guarding all within.', legacyAliases: [] },
  { id: 'yggdrasil_guardian', itemName: 'Yggdrasil Guardian Card', displayName: 'Yggdrasil Guardian', collectionNo: 'M-10', rarity: 'mythic', slot: 'accessory', art: '/assets/cards/yggdrasil_guardian.webp', abilityName: 'World Sap', stats: { hpBonus: 420, spBonus: 80 }, effect: { type: 'lifestealPct', value: 0.07 }, source: { kind: 'event', id: 'anniversary', label: 'Anniversary event', chance: 0.0035, pity: 150 }, lore: 'The world tree’s sap renews every root, vein, and breath.', legacyAliases: [] },
  { id: 'emperium_avatar', itemName: 'Emperium Avatar Card', displayName: 'Emperium Avatar', collectionNo: 'M-11', rarity: 'mythic', slot: 'shield', art: '/assets/cards/emperium_avatar.webp', abilityName: 'Realm Aegis', stats: { defBonus: 50 }, effect: { type: 'damageReduction', value: 0.07 }, source: { kind: 'event', id: 'guild_season', label: 'Guild season reward', chance: 0.0035, pity: 150 }, lore: 'A realm’s resolve gathers into a single unbreakable aegis.', legacyAliases: [] },
  { id: 'odins_echo', itemName: 'Odin’s Echo Card', displayName: 'Odin’s Echo', collectionNo: 'M-12', rarity: 'mythic', slot: 'weapon', art: '/assets/cards/odins_echo.webp', abilityName: 'Allfather’s Verdict', stats: { atkBonus: 60, critBonus: 0.07 }, effect: { type: 'damagePct', value: 0.1 }, source: { kind: 'event', id: 'celestial_collection', label: 'Celestial collection event', chance: 0.0035, pity: 150 }, lore: 'An ancient verdict rings through every strike with final authority.', legacyAliases: [] },
];

export const CARD_CATALOG = Object.freeze(records.map(card => Object.freeze({
  ...card,
  stats: Object.freeze({ ...card.stats }),
  effect: card.effect ? Object.freeze({ ...card.effect }) : null,
  source: Object.freeze({ ...card.source }),
  legacyAliases: Object.freeze([...(card.legacyAliases || [])]),
})));

export const CARD_BY_ID = new Map(CARD_CATALOG.map(card => [card.id, card]));
export const CARD_BY_ITEM_NAME = new Map();
for (const card of CARD_CATALOG) {
  CARD_BY_ITEM_NAME.set(card.itemName, card);
  for (const alias of card.legacyAliases) CARD_BY_ITEM_NAME.set(alias, card);
}

export function getCard(idOrName) {
  return CARD_BY_ID.get(idOrName) || CARD_BY_ITEM_NAME.get(idOrName) || null;
}

export function getCardsBySource(kind, id) {
  return CARD_CATALOG.filter(card => card.source.kind === kind && card.source.id === id);
}

export function toLegacyItem(card) {
  return {
    type: 'card',
    cardId: card.id,
    cardSlot: card.slot,
    rarity: card.rarity,
    art: card.art,
    card: { ...card.stats },
    desc: card.abilityName,
    price: 0,
  };
}
